# Generated by Django 5.2.1 on 2025-05-21 12:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('form', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='describtion',
            field=models.CharField(default=232, max_length=255),
            preserve_default=False,
        ),
    ]
